// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp.template.adaptor.adt
{
    using System.Linq;
    using System.Text;
    using System.IO;
    using System.Collections.Generic;
    using Kae.CIM.MetaModel.CIMofCIM;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class AzureDigitalTwinsAdaptorDef : AzureDigitalTwinsAdaptorDefBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 1 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"

  // Copyright (c) Knowledge & Experience. All rights reserved.
  // Licensed under the MIT license. See LICENSE file in the project root for full license information.

            
            #line default
            #line hidden
            this.Write("// ------------------------------------------------------------------------------" +
                    "\r\n// <auto-generated>\r\n//     This file is generated by tool.\r\n//     Runtime Ve" +
                    "rsion : ");
            
            #line 15 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(version));
            
            #line default
            #line hidden
            this.Write(@"
//  
// </auto-generated>
// ------------------------------------------------------------------------------
using Azure.Core;
using Kae.DomainModel.Csharp.Framework;
using Kae.DomainModel.Csharp.Framework.Adaptor;
using Kae.DomainModel.Csharp.Framework.Adaptor.ExternalStorage;
using Kae.DomainModel.Csharp.Framework.Adaptor.ExternalStorage.AzureDigitalTwins;
using Kae.Utility.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ");
            
            #line 31 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nameSpace));
            
            #line default
            #line hidden
            this.Write(".Adaptor\r\n{\r\n");
            
            #line 33 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"

    string classImplName = GetAdaptorImplClassName(projectName);

            
            #line default
            #line hidden
            this.Write("    public class ");
            
            #line 36 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classImplName));
            
            #line default
            #line hidden
            this.Write(" : AzureDigitalTwinsAdaptor\r\n    {\r\n\r\n        Dictionary<string, string> cClassTo" +
                    "TwinModel = new Dictionary<string, string>()\r\n        {\r\n");
            
            #line 41 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"

    int numOfObjDefs = objDefs.Count();
    int indexOfObjDefs = 0;
    foreach(var objDef in objDefs)
    {
        string twinModelId = GetTwinModelId(objDef);

            
            #line default
            #line hidden
            this.Write("            { \"");
            
            #line 48 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(objDef.Attr_Key_Lett));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 48 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(twinModelId));
            
            #line default
            #line hidden
            this.Write("\" }");
            
            #line 48 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
 if (++indexOfObjDefs < numOfObjDefs) { 
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 48 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 50 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"

    }

            
            #line default
            #line hidden
            this.Write("        };\r\n\r\n        Dictionary<string, DTDLRelationshipDef> cRelationshipToTwin" +
                    "Relationships = new Dictionary<string, DTDLRelationshipDef>()\r\n        {\r\n");
            
            #line 57 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"

    var dtdlRelDefs = new List<(string RelName, string RelId, string DTDLRelName, string SourceTwinModelId, string TargetTwinModelId, string FormClassKeyLetter, string PartClassKeyLetter)>();
    foreach(var relDef in relDefs)
    {
        var dtdlRelDefSet = GetRelationshipId(relDef);
        foreach(var dtdlRelDef in dtdlRelDefSet)
        {
            dtdlRelDefs.Add(dtdlRelDef);
        }
    }
    int numOfRelDefs = dtdlRelDefs.Count();
    int indexOfRelDefs = 0;
    foreach( var dtdlRelDef in dtdlRelDefs)
    {
        string relName = dtdlRelDef.RelName;
        string dtdlRelId = dtdlRelDef.RelId;
        string dtdlRelName = dtdlRelDef.DTDLRelName;
        string sourceTwinModelId = dtdlRelDef.SourceTwinModelId;
        string targetTwinModelId = dtdlRelDef.TargetTwinModelId;
        string partClassKey = dtdlRelDef.PartClassKeyLetter;
        string formClassKey = dtdlRelDef.FormClassKeyLetter;

            
            #line default
            #line hidden
            this.Write("            { \"");
            
            #line 79 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relName));
            
            #line default
            #line hidden
            this.Write("\", new DTDLRelationshipDef() { Id=\"");
            
            #line 79 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dtdlRelId));
            
            #line default
            #line hidden
            this.Write("\", Name=\"");
            
            #line 79 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dtdlRelName));
            
            #line default
            #line hidden
            this.Write("\", SourceTwinModelId=\"");
            
            #line 79 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sourceTwinModelId));
            
            #line default
            #line hidden
            this.Write("\", TargetTwinModelId=\"");
            
            #line 79 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(targetTwinModelId));
            
            #line default
            #line hidden
            this.Write("\", FormClassKeyLetter=\"");
            
            #line 79 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(formClassKey));
            
            #line default
            #line hidden
            this.Write("\", PartClassKeyLetter=\"");
            
            #line 79 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(partClassKey));
            
            #line default
            #line hidden
            this.Write("\" } }");
            
            #line 79 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
 if (++indexOfRelDefs < numOfRelDefs) { 
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 79 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 81 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"

    }

            
            #line default
            #line hidden
            this.Write("        };\r\n\r\n        public ");
            
            #line 86 "C:\Users\kae-m\source\repos\xtMULMetaModelProjects\Kae.XTUML.Tools.Generator.CodeOfDomainModel.Csharp\template\adaptor\adt\AzureDigitalTwinsAdaptorDef.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classImplName));
            
            #line default
            #line hidden
            this.Write(@"(string adtInstanceUrl, TokenCredential credential, InstanceRepository repository, Logger logger) : base(adtInstanceUrl, credential, repository, logger)
        {
            ;
        }

        public override DTDLRelationshipDef GetDTDLRelationshipDef(string domainName, string relationshipName)
        {
            return cRelationshipToTwinRelationships[relationshipName];
        }

        public override string GetDTDLTwinModelId(string domainName, string classKeyLetter)
        {
            return cClassToTwinModel[classKeyLetter];
        }

    }
}
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class AzureDigitalTwinsAdaptorDefBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
